### ISSUE TITLE
logging mouse speed

### ISSUE THREAD

**Issue by mohsenFN** [mhkarimi1383/MouseBench#1]
I think It's better to log cursor speed because it's really hard to see the mouse speed.
I have an idea, log the highest speed of cursor between two `0` speeds.
I know that its not an official project but anyway ...

**Comment by mhkarimi1383** [comment]
Your right I'm on research to find how to track mouse speed in dpi with html or javascript.
if find out how to do that plaese make a PR.

**Comment by mhkarimi1383** [comment]
but if you want listing I think it will decrease UI/UX but I we can add a download link and user will download looged data in a simple text file

**Comment by mhkarimi1383** [comment]
but I don't know how to do it

**Comment by mohsenFN** [comment]
yeah adding logger will definitely decrease UX. and saving logs in file seems creepy.
i don't know too.
